/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __fastcall start(__int64 a1, __int64 a2);
__int64 sub_1030();
void __fastcall sub_104C(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, char a9);
void __fastcall sub_10AC(int a1, _BYTE *a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, char a9);
void __fastcall sub_1440(_BYTE *a1, int a2, _BYTE *a3);
void sub_1618();
bool __fastcall sub_1660(unsigned __int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4);
__int64 __fastcall sub_1690(unsigned __int64 a1, unsigned __int64 a2, unsigned __int64 a3, unsigned __int64 a4);
unsigned __int64 __fastcall sub_180C(_BYTE *a1);
unsigned __int64 __fastcall sub_1824(_BYTE *a1);
void sub_18A0();
void __fastcall sub_18A8(__int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_1904(__int64 result, __int64 _X1, unsigned __int64 a3);
__int64 sub_1D98();
__int64 sub_1DD8();
__int64 sub_1E1C(void); // weak
__int64 __fastcall sub_1E20(__int64 a1);
void __fastcall sub_1F74(__int64 a1, __int64 a2);
__int64 __fastcall nullsub_1(_QWORD, _QWORD); // weak
__int64 __fastcall sub_2188(_QWORD, _QWORD); // weak
__int64 sub_218C();
__int64 __fastcall sub_2194(__int64 a1);
__int64 __fastcall sub_21FC(_BYTE *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8);
__int64 __fastcall sub_2340(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8);
_DWORD *__fastcall sub_2414(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8);
_DWORD *sub_27C8();
__int64 sub_27EC();
void sub_27F8();
__int64 __fastcall sub_2850(unsigned int a1, unsigned int a2, unsigned int a3, __int64 a4, __int64 a5);
__int64 sub_28FC();
__int64 sub_290C();
__int64 sub_291C();
__int64 __fastcall sub_292C(unsigned int a1, unsigned int a2, unsigned int a3, void *a4, void *a5, __int64 a6, unsigned __int64 a7);
void __fastcall sub_2B18(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8);
void __fastcall sub_2BBC(__int64 a1, __int64 a2);
bool __fastcall sub_2C10(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_2C80(__int64 a1, __int64 a2);
unsigned __int64 sub_2D10();
__int64 __fastcall sub_2DEC(_QWORD, _QWORD); // weak
__int64 __fastcall sub_2DF0(__int64 a1, __int64 a2);
__int64 sub_2E30();
unsigned __int64 __fastcall sub_2E38(_QWORD *a1, _QWORD *a2);
unsigned __int64 sub_2F14();
__int64 sub_2FA0();
unsigned __int64 sub_3044();
__int64 sub_30D0();
_DWORD *__fastcall sub_3108(unsigned __int16 a1, _DWORD *a2);
_DWORD *__fastcall sub_316C(_QWORD *a1, _DWORD *a2);
_DWORD *__fastcall sub_31BC(_QWORD *a1);
__int64 sub_31E4();
_QWORD *__fastcall sub_320C(_QWORD *result, __int64 a2);
void sub_33C4();
__int64 __fastcall sub_34A8(__int64 a1, __int64 a2);
void sub_3508();
void sub_3510();
void sub_3518();
void sub_3520();
__int64 sub_3528();
unsigned __int64 sub_3530();
__int64 sub_3538();
__int64 __fastcall sub_3558(__int64 a1, __int64 a2);
void __fastcall sub_35BC(__int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_35F0(__int64 a1, unsigned __int64 a2, unsigned __int64 a3, __int64 a4);
void sub_3650();
__int64 __fastcall sub_36A8(unsigned __int64 a1, unsigned __int64 a2, __int64 a3);
void __fastcall sub_36C8(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, char a9);
void __fastcall sub_3718(unsigned int a1, unsigned __int64 *a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, char a9);
unsigned __int64 sub_3814();
unsigned __int64 sub_381C();
unsigned __int64 sub_3824();
unsigned __int64 sub_382C();
unsigned __int64 sub_3834();
unsigned __int64 sub_383C();
unsigned __int64 sub_3844();
unsigned __int64 sub_384C();
unsigned __int64 sub_3854();
unsigned __int64 sub_385C();
unsigned __int64 sub_3864();

//-------------------------------------------------------------------------
// Data declarations

__int64 qword_5000 = 3233857728LL; // weak
_UNKNOWN unk_5008; // weak
char *off_5018 = "ChargerExDxe"; // weak
_QWORD qword_5020[2] = { 5577249026876304060LL, 332469257585636247LL }; // weak
_UNKNOWN unk_5030; // weak
_UNKNOWN unk_5040; // weak
_QWORD qword_5050[2] = { 4761552760513311930LL, -5103829374540632427LL }; // weak
_QWORD qword_5060[2] = { 1284814347334971980LL, 5602828850577816218LL }; // weak
_UNKNOWN unk_5070; // weak
_UNKNOWN unk_5080; // weak
_UNKNOWN unk_5090; // weak
_UNKNOWN unk_50A0; // weak
_UNKNOWN unk_50C0; // weak
_UNKNOWN unk_50D0; // weak
_UNKNOWN unk_50E0; // weak
_UNKNOWN *off_5150 = NULL; // weak
_UNKNOWN *off_5158 = NULL; // weak
_UNKNOWN *off_5160 = NULL; // weak
_UNKNOWN *off_5168 = NULL; // weak
__int64 qword_5170 = 0LL; // weak
__int64 qword_5178 = 0LL; // weak
__int64 qword_5180 = 0LL; // weak
_UNKNOWN *off_5188 = NULL; // weak
int dword_5190 = 0; // weak
__int64 qword_5198 = 0LL; // weak
__int64 qword_51A0 = 0LL; // weak
__int64 qword_51A8 = 0LL; // weak
__int64 qword_51B0 = 0LL; // weak
__int64 qword_51B8 = 0LL; // weak
__int64 qword_51C0 = 0LL; // weak


//----- (0000000000001000) ----------------------------------------------------
void __fastcall start(__int64 a1, __int64 a2)
{
  char v2; // w30
  __int64 v3; // x19
  __int64 v4; // x20
  __int64 v5; // x0
  __int64 v6; // x1
  __int64 v7; // x2
  __int64 v8; // x3
  __int64 v9; // x4
  __int64 v10; // x5
  __int64 v11; // x6
  __int64 v12; // x7
  __int64 v13; // x0
  __int64 v14; // x1
  char v15; // [xsp+0h] [xbp-40h]
  __int64 v16; // [xsp+8h] [xbp-38h]
  __int64 v17; // [xsp+20h] [xbp-20h]
  __int64 v18; // [xsp+28h] [xbp-18h]

  if ( a1 )
  {
    v17 = a2;
    v18 = a1;
    v15 = v2;
    sub_1030();
    a2 = v17;
    a1 = v18;
  }
  v3 = a2;
  v4 = a1;
  v16 = qword_5000;
  sub_1F74(a1, a2);
  v5 = sub_2188(v4, v3);
  if ( v5 < 0 )
    v5 = nullsub_1(v4, v3);
  if ( qword_5000 != v16 )
  {
    sub_104C(v5, v6, v7, v8, v9, v10, v11, v12, v15);
    sub_1F74(v13, v14);
  }
}
// 1014: variable 'v2' is possibly undefined
// 1F70: variable 'v6' is possibly undefined
// 1F70: variable 'v7' is possibly undefined
// 1F70: variable 'v8' is possibly undefined
// 1F70: variable 'v9' is possibly undefined
// 1F70: variable 'v10' is possibly undefined
// 1F70: variable 'v11' is possibly undefined
// 1F70: variable 'v12' is possibly undefined
// 1F70: variable 'v15' is possibly undefined
// 1F71: variable 'v13' is possibly undefined
// 1F71: variable 'v14' is possibly undefined
// 2184: using guessed type __int64 __fastcall nullsub_1(_QWORD, _QWORD);
// 2188: using guessed type __int64 __fastcall sub_2188(_QWORD, _QWORD);
// 5000: using guessed type __int64 qword_5000;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000001030) ----------------------------------------------------
__int64 sub_1030()
{
  __int64 result; // x0

  result = sub_1E1C();
  qword_5000 = result;
  return result;
}
// 1E1C: using guessed type __int64 sub_1E1C(void);
// 5000: using guessed type __int64 qword_5000;

//----- (000000000000104C) ----------------------------------------------------
void __fastcall sub_104C(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        char a9)
{
  __int64 v9; // x0
  int v10; // w0
  _BYTE *v11; // x1
  __int64 v12; // x2
  __int64 v13; // x3
  __int64 v14; // x4
  __int64 v15; // x5
  __int64 v16; // x6
  __int64 v17; // x7
  char v18; // [xsp+0h] [xbp-10h]
  int v19; // [xsp+4h] [xbp-Ch]
  __int64 v20; // [xsp+8h] [xbp-8h]

  v20 = qword_5000;
  sub_10AC(0x80000000, "__stack_chk_fail : Stack corruption detected \n", a3, a4, a5, a6, a7, a8, v18);
  v9 = sub_1DD8();
  while ( v19 )
    ;
  if ( qword_5000 != v20 )
  {
    v10 = sub_104C(v9);
    sub_10AC(v10, v11, v12, v13, v14, v15, v16, v17, a9);
  }
}
// 1078: variable 'v18' is possibly undefined
// 1084: variable 'v19' is possibly undefined
// 10A9: variable 'v11' is possibly undefined
// 10A9: variable 'v12' is possibly undefined
// 10A9: variable 'v13' is possibly undefined
// 10A9: variable 'v14' is possibly undefined
// 10A9: variable 'v15' is possibly undefined
// 10A9: variable 'v16' is possibly undefined
// 10A9: variable 'v17' is possibly undefined
// 5000: using guessed type __int64 qword_5000;

//----- (00000000000010AC) ----------------------------------------------------
void __fastcall sub_10AC(
        int a1,
        _BYTE *a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        char a9)
{
  _BYTE *v9; // x19
  unsigned __int64 v11; // x0
  unsigned __int64 v12; // x20
  __int64 *v13; // x24
  char v14; // w11
  int v15; // w13
  unsigned int v16; // t1
  __int64 v17; // x15
  bool v18; // zf
  __int64 v19; // x14
  char *v20; // x17
  int v21; // w13
  __int64 v22; // x15
  char *v23; // x3
  __int64 v24; // x12
  char *v25; // x1
  __int64 v26; // x11
  char *v27; // x2
  char *v28; // x0
  __int64 v29; // x16
  char *v30; // x4
  _BYTE *v31; // x0
  int v32; // w1
  _BYTE *v33; // x2
  _QWORD v34[7]; // [xsp+80h] [xbp-170h] BYREF
  char *v35; // [xsp+B8h] [xbp-138h] BYREF
  char **v36; // [xsp+C0h] [xbp-130h]
  _QWORD *v37; // [xsp+C8h] [xbp-128h]
  int v38; // [xsp+D0h] [xbp-120h]
  int v39; // [xsp+D4h] [xbp-11Ch]
  int v40; // [xsp+DCh] [xbp-114h] BYREF
  __int64 v41; // [xsp+E0h] [xbp-110h] BYREF
  _BYTE v42[104]; // [xsp+140h] [xbp-B0h] BYREF
  __int64 v43; // [xsp+1A8h] [xbp-48h]

  v9 = a2;
  v34[5] = a7;
  v34[6] = a8;
  v34[3] = a5;
  v34[4] = a6;
  v34[1] = a3;
  v34[2] = a4;
  v43 = qword_5000;
  if ( !a2 )
  {
    sub_1440("DebugLib.c", 68, "Format != ((void *) 0)");
    while ( 1 )
      ;
  }
  v11 = sub_27EC();
  if ( ((unsigned int)v11 & a1) != 0 )
  {
    v11 = sub_180C(v9);
    v12 = v11 + 104;
    if ( v11 + 104 <= 0xD0 )
    {
      v40 = a1;
      v13 = &v41;
      sub_1690((unsigned __int64)v42, 0x68u, (unsigned __int64)v9, 0x68u);
      v35 = &a9;
      v38 = -48;
      v39 = -128;
      v36 = &v35;
      v37 = v34;
      while ( 1 )
      {
        if ( *v9 == 37 )
        {
          v14 = 0;
          while ( 1 )
          {
            while ( 1 )
            {
              do
              {
                v16 = (unsigned __int8)*++v9;
                v15 = v16;
                v17 = (1LL << v16) & 0x680100000000LL;
                v18 = v16 > 0x2E || v17 == 0;
              }
              while ( !v18 || (unsigned int)(v15 - 48) < 0xA );
              if ( v15 <= 75 )
                break;
              if ( v15 != 108 && v15 != 76 )
                goto LABEL_29;
              v14 = 1;
            }
            if ( v15 != 42 )
              break;
            v19 = v38;
            if ( v38 < 0 && (v38 += 8, (int)v19 + 8 <= 0) )
            {
              v20 = (char *)v36 + v19;
            }
            else
            {
              v20 = v35;
              v35 += 8;
            }
            *v13++ = *(_QWORD *)v20;
          }
          if ( !v15 )
            --v9;
LABEL_29:
          v21 = (unsigned __int8)*v9;
          switch ( *v9 )
          {
            case 'a':
            case 'g':
            case 's':
            case 't':
              goto LABEL_42;
            case 'b':
            case 'e':
            case 'f':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'q':
            case 'v':
            case 'w':
              goto LABEL_54;
            case 'c':
              v22 = v38;
              if ( v38 < 0 && (v38 += 8, (int)v22 + 8 <= 0) )
              {
                v23 = (char *)v36 + v22;
              }
              else
              {
                v23 = v35;
                v35 += 8;
              }
              *v13++ = *(_QWORD *)v23;
              goto LABEL_54;
            case 'd':
            case 'p':
            case 'u':
            case 'x':
              goto LABEL_36;
            case 'r':
              v29 = v38;
              if ( v38 < 0 && (v38 += 8, (int)v29 + 8 <= 0) )
              {
                v30 = (char *)v36 + v29;
              }
              else
              {
                v30 = v35;
                v35 += 8;
              }
              *v13++ = *(_QWORD *)v30;
              goto LABEL_54;
            default:
              if ( v21 == 83 )
              {
LABEL_42:
                v26 = v38;
                if ( v38 < 0 && (v38 += 8, (int)v26 + 8 <= 0) )
                {
                  v27 = (char *)v36 + v26;
                }
                else
                {
                  v27 = v35;
                  v35 += 8;
                }
                *v13++ = *(_QWORD *)v27;
              }
              else if ( v21 == 88 )
              {
LABEL_36:
                v24 = v38;
                if ( v14 || v21 == 112 )
                {
                  if ( v38 < 0 && (v38 += 8, (int)v24 + 8 <= 0) )
                  {
                    v28 = (char *)v36 + v24;
                  }
                  else
                  {
                    v28 = v35;
                    v35 += 8;
                  }
                  *v13++ = *(_QWORD *)v28;
                }
                else
                {
                  if ( v38 < 0 && (v38 += 8, (int)v24 + 8 <= 0) )
                  {
                    v25 = (char *)v36 + v24;
                  }
                  else
                  {
                    v25 = v35;
                    v35 += 8;
                  }
                  *(_DWORD *)v13++ = *(_QWORD *)v25;
                }
              }
LABEL_54:
              if ( v13 > (__int64 *)v42 )
              {
                sub_1440("DebugLib.c", 206, "(CHAR8 *)BaseListMarker <= FormatString");
                while ( 1 )
                  ;
              }
              break;
          }
        }
        else if ( !*v9 )
        {
          sub_28FC();
          sub_290C();
          v11 = sub_291C();
          if ( (_BYTE)v11 )
            v11 = sub_292C(3u, 0x3050000u, 0, 0, &unk_5040, (__int64)&v40, v12);
          break;
        }
        ++v9;
      }
    }
  }
  if ( qword_5000 != v43 )
  {
    v31 = (_BYTE *)sub_104C(v11);
    sub_1440(v31, v32, v33);
  }
}
// 143D: variable 'v32' is possibly undefined
// 143D: variable 'v33' is possibly undefined
// 104C: using guessed type __int64 __fastcall sub_104C(_QWORD);
// 5000: using guessed type __int64 qword_5000;

//----- (0000000000001440) ----------------------------------------------------
void __fastcall sub_1440(_BYTE *a1, int a2, _BYTE *a3)
{
  unsigned __int64 v6; // x26
  unsigned __int64 v7; // x19
  unsigned __int64 v8; // x0
  unsigned __int64 v9; // x21
  unsigned __int64 v10; // x27
  __int64 v11; // x0
  _BYTE v12[20]; // [xsp+10h] [xbp-120h] BYREF
  int v13; // [xsp+24h] [xbp-10Ch]
  char v14; // [xsp+38h] [xbp-F8h] BYREF
  _BYTE v15[7]; // [xsp+39h] [xbp-F7h] BYREF
  __int64 v16; // [xsp+D8h] [xbp-58h]

  v16 = qword_5000;
  v6 = sub_180C(off_5018);
  v7 = sub_180C(a1);
  v8 = sub_180C(a3);
  v9 = v8;
  if ( v6 + v7 + v8 + 42 < 0xC9 )
  {
    v13 = a2;
    v10 = v6 + 2;
    if ( v6 != -2 )
    {
      sub_1904((__int64)&v14, (__int64)"[", 1u);
      sub_1904((__int64)v15, (__int64)off_5018, v6 - 1);
      sub_1904((__int64)&v15[v6 - 1], (__int64)"] ", 2u);
    }
  }
  else
  {
    if ( v7 + 40 + v8 >= 0xC9 )
    {
      if ( v7 + 40 < 0xC8 )
      {
        v9 = 160 - v7;
      }
      else
      {
        v7 = 159;
        v9 = 1;
      }
    }
    v13 = a2;
    v10 = 0;
  }
  v11 = sub_1904((__int64)&v15[v10 - 1], (__int64)a1, v7) + v7;
  *(_BYTE *)(v11 - 1) = 0;
  *(_BYTE *)(sub_1904(v11, (__int64)a3, v9) + v9 - 1) = 0;
  sub_28FC();
  if ( (unsigned __int8)sub_290C() )
    sub_292C(0x90000002, 0x3050007u, 0, 0, 0, (__int64)v12, v9 + v7 + v10 + 40);
  else
    sub_291C();
  sub_1618();
  if ( qword_5000 != v16 )
  {
    sub_104C();
    sub_1618();
  }
}
// 104C: using guessed type __int64 sub_104C(void);
// 5000: using guessed type __int64 qword_5000;
// 5018: using guessed type char *off_5018;

//----- (0000000000001618) ----------------------------------------------------
void sub_1618()
{
  while ( 1 )
    ;
}
// 1638: conditional instruction was optimized away because %var_10.8==0
// 104C: using guessed type __int64 sub_104C(void);
// 5000: using guessed type __int64 qword_5000;

//----- (0000000000001660) ----------------------------------------------------
bool __fastcall sub_1660(unsigned __int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4)
{
  bool v4; // cf
  _BOOL8 result; // x0

  v4 = a1 < a3 || a1 >= a3 + a4;
  result = 1;
  if ( v4 && (a3 < a1 || a3 >= a1 + a2) )
    return 0;
  return result;
}

//----- (0000000000001690) ----------------------------------------------------
__int64 __fastcall sub_1690(unsigned __int64 a1, unsigned __int64 a2, unsigned __int64 a3, unsigned __int64 a4)
{
  char *v4; // x20
  _BYTE *v5; // x19
  unsigned __int64 i; // x8
  unsigned __int64 v7; // x21
  char v8; // w8

  v4 = (char *)a3;
  v5 = (_BYTE *)a1;
  if ( !a1 )
  {
    sub_1440("SafeString.c", 670, "(Destination != ((void *) 0))");
    while ( 1 )
      ;
  }
  if ( !a3 )
  {
    sub_1440("SafeString.c", 671, "(Source != ((void *) 0))");
    while ( 1 )
      ;
  }
  if ( a2 > 0xF4240 )
  {
    sub_1440("SafeString.c", 677, "(DestMax <= (_gPcd_FixedAtBuild_PcdMaximumAsciiStringLength))");
    while ( 1 )
      ;
  }
  if ( a4 > 0xF4240 )
  {
    sub_1440("SafeString.c", 678, "(Length <= (_gPcd_FixedAtBuild_PcdMaximumAsciiStringLength))");
    while ( 1 )
      ;
  }
  if ( !a2 )
  {
    sub_1440("SafeString.c", 684, "(DestMax != 0)");
    while ( 1 )
      ;
  }
  for ( i = 0; i < a2; ++i )
  {
    if ( !*(_BYTE *)(a3 + i) )
      goto LABEL_22;
  }
  if ( a4 >= a2 )
  {
    sub_1440("SafeString.c", 691, "(DestMax > SourceLen)");
    while ( 1 )
      ;
  }
LABEL_22:
  if ( i <= a4 )
    v7 = i;
  else
    v7 = a4;
  if ( sub_1660(a1, a2, a3, v7 + 1) )
  {
    sub_1440(
      "SafeString.c",
      700,
      "InternalSafeStringNoAsciiStrOverlap (Destination, DestMax, (CHAR8 *)Source, SourceLen + 1)");
    while ( 1 )
      ;
  }
  while ( v7 )
  {
    v8 = *v4;
    if ( !*v4 )
      break;
    ++v4;
    *v5++ = v8;
    --v7;
  }
  *v5 = 0;
  return 0;
}

//----- (000000000000180C) ----------------------------------------------------
unsigned __int64 __fastcall sub_180C(_BYTE *a1)
{
  return sub_1824(a1) + 1;
}

//----- (0000000000001824) ----------------------------------------------------
unsigned __int64 __fastcall sub_1824(_BYTE *a1)
{
  unsigned __int64 v1; // x8

  if ( !a1 )
  {
    sub_1440("String.c", 1294, "String != ((void *) 0)");
    while ( 1 )
      ;
  }
  v1 = 0;
  while ( *a1 )
  {
    if ( v1 >= 0xF4240 )
    {
      sub_1440("String.c", 1302, "Length < _gPcd_FixedAtBuild_PcdMaximumAsciiStringLength");
      while ( 1 )
        ;
    }
    ++a1;
    ++v1;
  }
  return v1;
}
// 1440: using guessed type __int64 __fastcall sub_1440(_QWORD, _QWORD, _QWORD);

//----- (00000000000018A0) ----------------------------------------------------
void sub_18A0()
{
  __asm { SVC             0xDBDB }
}

//----- (00000000000018A8) ----------------------------------------------------
void __fastcall sub_18A8(__int64 a1, unsigned __int64 a2)
{
  if ( !a1 && a2 )
  {
    sub_1440("ZeroMemWrapper.c", 49, "!(Buffer == ((void *) 0) && Length > 0)");
    while ( 1 )
      ;
  }
  if ( a2 > -a1 )
  {
    sub_1440("ZeroMemWrapper.c", 50, "Length <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)Buffer + 1)");
    while ( 1 )
      ;
  }
  JUMPOUT(0x19A4);
}
// 1900: control flows out of bounds to 19A4

//----- (0000000000001904) ----------------------------------------------------
__int64 __fastcall sub_1904(__int64 result, __int64 _X1, unsigned __int64 a3)
{
  __int64 v7; // x4
  __int64 v8; // x5
  __int64 v9; // x6
  __int64 v10; // x7
  __int64 v11; // x12
  __int64 v12; // x13
  __int64 v13; // x9
  __int64 v14; // x10
  __int64 v15; // x11
  __int64 v16; // x7
  int v17; // w7
  char v18; // w7
  char v19; // w8
  __int64 v20; // x8
  __int64 v21; // x9
  __int64 v22; // x10
  __int64 v23; // x11
  __int64 v24; // x12
  __int64 v25; // x13
  __int64 v26; // x14
  __int64 v27; // x15
  __int64 v28; // x3
  __int64 v29; // x4
  __int64 v30; // t2
  _QWORD *v31; // x3
  __int64 v32; // x12
  __int64 v33; // x13
  _QWORD *v34; // x1
  unsigned __int64 v35; // x2
  __int64 v36; // x6
  __int64 v37; // x7
  __int64 v38; // x8
  __int64 v39; // x9
  __int64 v40; // x10
  __int64 v41; // x11
  _QWORD *v42; // x1
  __int64 v43; // x12
  __int64 v44; // x13
  bool v45; // cc
  unsigned __int64 i; // x2
  __int64 v47; // x14
  __int64 v48; // x15
  __int64 v49; // x6
  __int64 v50; // x7
  __int64 v51; // x8
  __int64 v52; // x9
  __int64 v53; // x10
  __int64 v54; // x11
  unsigned __int64 v55; // x3
  __int64 v57; // x5
  __int64 v58; // x3
  __int64 v59; // x12
  __int64 v60; // x13
  unsigned __int64 v61; // x4
  unsigned __int64 v62; // x2
  __int64 v63; // x6
  __int64 v64; // x7
  __int64 v65; // x8
  __int64 v66; // x9
  __int64 v67; // x10
  __int64 v68; // x11
  unsigned __int64 v69; // x4
  __int64 v70; // x12
  __int64 v71; // x13
  __int64 v72; // x5
  unsigned __int64 j; // x2
  __int64 v74; // x14
  __int64 v75; // x15
  __int64 v76; // x6
  __int64 v77; // x7
  __int64 v78; // x8
  __int64 v79; // x9
  __int64 v80; // x10
  __int64 v81; // x11

  if ( a3 )
  {
    if ( a3 - 1 > ~result )
    {
      sub_1440("CopyMemWrapper.c", 56, "(Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)DestinationBuffer)");
      while ( 1 )
        ;
    }
    if ( a3 - 1 > ~_X1 )
    {
      sub_1440("CopyMemWrapper.c", 57, "(Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)SourceBuffer)");
      while ( 1 )
        ;
    }
    if ( result != _X1 )
    {
      v55 = result - _X1;
      if ( a3 <= 0x60 || v55 >= a3 )
      {
        __asm { PRFM            #0, [X1] }
        v7 = _X1 + a3;
        v8 = result + a3;
        if ( a3 <= 0x10 )
        {
          if ( a3 < 8 )
          {
            if ( (a3 & 4) != 0 )
            {
              v17 = *(_DWORD *)(v7 - 4);
              *(_DWORD *)result = *(_DWORD *)_X1;
              *(_DWORD *)(v8 - 4) = v17;
            }
            else
            {
              v18 = *(_BYTE *)(v7 - 1);
              v19 = *(_BYTE *)(_X1 + (a3 >> 1));
              *(_BYTE *)result = *(_BYTE *)_X1;
              *(_BYTE *)(result + (a3 >> 1)) = v19;
              *(_BYTE *)(v8 - 1) = v18;
            }
          }
          else
          {
            v16 = *(_QWORD *)(v7 - 8);
            *(_QWORD *)result = *(_QWORD *)_X1;
            *(_QWORD *)(v8 - 8) = v16;
          }
        }
        else if ( a3 > 0x60 )
        {
          v31 = (_QWORD *)(result & 0xFFFFFFFFFFFFFFF0uLL);
          v32 = *(_QWORD *)_X1;
          v33 = *(_QWORD *)(_X1 + 8);
          v34 = (_QWORD *)(_X1 - (result & 0xF));
          v35 = a3 + (result & 0xF);
          v36 = v34[2];
          v37 = v34[3];
          *(_QWORD *)result = v32;
          *(_QWORD *)(result + 8) = v33;
          v38 = v34[4];
          v39 = v34[5];
          v40 = v34[6];
          v41 = v34[7];
          v43 = v34[8];
          v44 = v34[9];
          v42 = v34 + 8;
          v45 = v35 > 0x90;
          for ( i = v35 - 144; v45; i -= 64LL )
          {
            v31[2] = v36;
            v31[3] = v37;
            v36 = v42[2];
            v37 = v42[3];
            v31[4] = v38;
            v31[5] = v39;
            v38 = v42[4];
            v39 = v42[5];
            v31[6] = v40;
            v31[7] = v41;
            v40 = v42[6];
            v41 = v42[7];
            v31[8] = v43;
            v31[9] = v44;
            v31 += 8;
            v43 = v42[8];
            v44 = v42[9];
            v42 += 8;
            v45 = i > 0x40;
          }
          v47 = *(_QWORD *)(v7 - 64);
          v48 = *(_QWORD *)(v7 - 56);
          v31[2] = v36;
          v31[3] = v37;
          v49 = *(_QWORD *)(v7 - 48);
          v50 = *(_QWORD *)(v7 - 40);
          v31[4] = v38;
          v31[5] = v39;
          v51 = *(_QWORD *)(v7 - 32);
          v52 = *(_QWORD *)(v7 - 24);
          v31[6] = v40;
          v31[7] = v41;
          v53 = *(_QWORD *)(v7 - 16);
          v54 = *(_QWORD *)(v7 - 8);
          v31[8] = v43;
          v31[9] = v44;
          *(_QWORD *)(v8 - 64) = v47;
          *(_QWORD *)(v8 - 56) = v48;
          *(_QWORD *)(v8 - 48) = v49;
          *(_QWORD *)(v8 - 40) = v50;
          *(_QWORD *)(v8 - 32) = v51;
          *(_QWORD *)(v8 - 24) = v52;
          *(_QWORD *)(v8 - 16) = v53;
          *(_QWORD *)(v8 - 8) = v54;
        }
        else
        {
          v9 = *(_QWORD *)_X1;
          v10 = *(_QWORD *)(_X1 + 8);
          if ( (((_DWORD)a3 - 1) & 0x40) != 0 )
          {
            v20 = *(_QWORD *)(_X1 + 16);
            v21 = *(_QWORD *)(_X1 + 24);
            v22 = *(_QWORD *)(_X1 + 32);
            v23 = *(_QWORD *)(_X1 + 40);
            v24 = *(_QWORD *)(_X1 + 48);
            v25 = *(_QWORD *)(_X1 + 56);
            v26 = *(_QWORD *)(v7 - 32);
            v27 = *(_QWORD *)(v7 - 24);
            v30 = v7 - 16;
            v29 = *(_QWORD *)(v7 - 16);
            v28 = *(_QWORD *)(v30 + 8);
            *(_QWORD *)result = v9;
            *(_QWORD *)(result + 8) = v10;
            *(_QWORD *)(result + 16) = v20;
            *(_QWORD *)(result + 24) = v21;
            *(_QWORD *)(result + 32) = v22;
            *(_QWORD *)(result + 40) = v23;
            *(_QWORD *)(result + 48) = v24;
            *(_QWORD *)(result + 56) = v25;
            *(_QWORD *)(v8 - 32) = v26;
            *(_QWORD *)(v8 - 24) = v27;
            *(_QWORD *)(v8 - 16) = v29;
            *(_QWORD *)(v8 - 8) = v28;
          }
          else
          {
            v11 = *(_QWORD *)(v7 - 16);
            v12 = *(_QWORD *)(v7 - 8);
            if ( (((_BYTE)a3 - 1) & 0x20) != 0 )
            {
              v13 = *(_QWORD *)(_X1 + 24);
              v14 = *(_QWORD *)(v7 - 32);
              v15 = *(_QWORD *)(v7 - 24);
              *(_QWORD *)(result + 16) = *(_QWORD *)(_X1 + 16);
              *(_QWORD *)(result + 24) = v13;
              *(_QWORD *)(v8 - 32) = v14;
              *(_QWORD *)(v8 - 24) = v15;
            }
            *(_QWORD *)result = v9;
            *(_QWORD *)(result + 8) = v10;
            *(_QWORD *)(v8 - 16) = v11;
            *(_QWORD *)(v8 - 8) = v12;
          }
        }
      }
      else if ( v55 )
      {
        v57 = result + a3;
        v58 = (result + a3) & 0xF;
        v59 = *(_QWORD *)(_X1 + a3 - 16);
        v60 = *(_QWORD *)(_X1 + a3 - 8);
        v61 = _X1 + a3 - v58;
        v62 = a3 - v58;
        v63 = *(_QWORD *)(v61 - 16);
        v64 = *(_QWORD *)(v61 - 8);
        *(_QWORD *)(v57 - 16) = v59;
        *(_QWORD *)(v57 - 8) = v60;
        v65 = *(_QWORD *)(v61 - 32);
        v66 = *(_QWORD *)(v61 - 24);
        v67 = *(_QWORD *)(v61 - 48);
        v68 = *(_QWORD *)(v61 - 40);
        v70 = *(_QWORD *)(v61 - 64);
        v71 = *(_QWORD *)(v61 - 56);
        v69 = v61 - 64;
        v72 = v57 - v58;
        v45 = v62 > 0x80;
        for ( j = v62 - 128; v45; j -= 64LL )
        {
          *(_QWORD *)(v72 - 16) = v63;
          *(_QWORD *)(v72 - 8) = v64;
          v63 = *(_QWORD *)(v69 - 16);
          v64 = *(_QWORD *)(v69 - 8);
          *(_QWORD *)(v72 - 32) = v65;
          *(_QWORD *)(v72 - 24) = v66;
          v65 = *(_QWORD *)(v69 - 32);
          v66 = *(_QWORD *)(v69 - 24);
          *(_QWORD *)(v72 - 48) = v67;
          *(_QWORD *)(v72 - 40) = v68;
          v67 = *(_QWORD *)(v69 - 48);
          v68 = *(_QWORD *)(v69 - 40);
          *(_QWORD *)(v72 - 64) = v70;
          *(_QWORD *)(v72 - 56) = v71;
          v72 -= 64;
          v70 = *(_QWORD *)(v69 - 64);
          v71 = *(_QWORD *)(v69 - 56);
          v69 -= 64LL;
          v45 = j > 0x40;
        }
        v74 = *(_QWORD *)(_X1 + 48);
        v75 = *(_QWORD *)(_X1 + 56);
        *(_QWORD *)(v72 - 16) = v63;
        *(_QWORD *)(v72 - 8) = v64;
        v76 = *(_QWORD *)(_X1 + 32);
        v77 = *(_QWORD *)(_X1 + 40);
        *(_QWORD *)(v72 - 32) = v65;
        *(_QWORD *)(v72 - 24) = v66;
        v78 = *(_QWORD *)(_X1 + 16);
        v79 = *(_QWORD *)(_X1 + 24);
        *(_QWORD *)(v72 - 48) = v67;
        *(_QWORD *)(v72 - 40) = v68;
        v80 = *(_QWORD *)_X1;
        v81 = *(_QWORD *)(_X1 + 8);
        *(_QWORD *)(v72 - 64) = v70;
        *(_QWORD *)(v72 - 56) = v71;
        *(_QWORD *)(result + 48) = v74;
        *(_QWORD *)(result + 56) = v75;
        *(_QWORD *)(result + 32) = v76;
        *(_QWORD *)(result + 40) = v77;
        *(_QWORD *)(result + 16) = v78;
        *(_QWORD *)(result + 24) = v79;
        *(_QWORD *)result = v80;
        *(_QWORD *)(result + 8) = v81;
      }
    }
  }
  return result;
}
// 1C08: conditional instruction was optimized away because x2.8 is in (1..7)
// 1440: using guessed type __int64 __fastcall sub_1440(_QWORD, _QWORD, _QWORD);

//----- (0000000000001D98) ----------------------------------------------------
__int64 sub_1D98()
{
  _DWORD *v0; // x0

  v0 = sub_27C8();
  if ( v0 )
    return (*((__int64 (__fastcall **)(const char *, _QWORD, _UNKNOWN **))v0 + 2))("SerialPort Lib", 0, &off_5150);
  else
    return 0x8000000000000007uLL;
}
// 5150: using guessed type _UNKNOWN *off_5150;

//----- (0000000000001DD8) ----------------------------------------------------
__int64 sub_1DD8()
{
  __int64 (**v0)(void); // x8

  v0 = (__int64 (**)(void))off_5150;
  if ( off_5150 )
    return v0[5]();
  sub_1D98();
  v0 = (__int64 (**)(void))off_5150;
  if ( off_5150 )
    return v0[5]();
  else
    return 0;
}
// 5150: using guessed type _UNKNOWN *off_5150;

//----- (0000000000001E20) ----------------------------------------------------
__int64 __fastcall sub_1E20(__int64 a1)
{
  __int64 v2; // x19

  v2 = sub_218C();
  if ( (v2 & 0x8000000000000000uLL) == 0 )
    nullsub_1(a1, qword_5180);
  return v2;
}
// 2184: using guessed type __int64 __fastcall nullsub_1(_QWORD, _QWORD);
// 5180: using guessed type __int64 qword_5180;

//----- (0000000000001F74) ----------------------------------------------------
void __fastcall sub_1F74(__int64 a1, __int64 a2)
{
  __int64 v4; // x3
  __int64 v5; // x4
  __int64 v6; // x5
  __int64 v7; // x6
  __int64 v8; // x7
  __int64 v9; // x8
  __int64 v10; // x3
  __int64 v11; // x4
  __int64 v12; // x5
  __int64 v13; // x6
  __int64 v14; // x7
  __int64 v15; // x9
  __int64 v16; // x3
  __int64 v17; // x4
  __int64 v18; // x5
  __int64 v19; // x6
  __int64 v20; // x7
  __int64 v21; // x10
  __int64 v22; // x3
  __int64 v23; // x4
  __int64 v24; // x5
  __int64 v25; // x6
  __int64 v26; // x7
  __int64 v27; // x11
  __int64 v28; // x3
  __int64 v29; // x4
  __int64 v30; // x5
  __int64 v31; // x6
  __int64 v32; // x7
  unsigned __int64 v33; // x12
  __int64 v34; // x3
  __int64 v35; // x4
  __int64 v36; // x5
  __int64 v37; // x6
  __int64 v38; // x7
  __int64 v39; // x13
  __int64 v40; // x3
  __int64 v41; // x4
  __int64 v42; // x5
  __int64 v43; // x6
  __int64 v44; // x7
  unsigned __int64 v45; // x14
  __int64 v46; // x3
  __int64 v47; // x4
  __int64 v48; // x5
  __int64 v49; // x6
  __int64 v50; // x7
  __int64 v51; // x15
  char v52; // [xsp+0h] [xbp-10h]

  v9 = sub_2C80(a1, a2);
  if ( v9 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v9, v4, v5, v6, v7, v8, v52);
    sub_1440("AutoGen.c", 415, "!EFI_ERROR (Status)");
  }
  v15 = sub_2DEC(a1, a2);
  if ( v15 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v15, v10, v11, v12, v13, v14, v52);
    sub_1440("AutoGen.c", 418, "!EFI_ERROR (Status)");
  }
  v21 = sub_2DF0(a1, a2);
  if ( v21 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v21, v16, v17, v18, v19, v20, v52);
    sub_1440("AutoGen.c", 421, "!EFI_ERROR (Status)");
  }
  v27 = sub_2E30();
  if ( v27 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v27, v22, v23, v24, v25, v26, v52);
    sub_1440("AutoGen.c", 424, "!EFI_ERROR (Status)");
  }
  v33 = sub_2F14();
  if ( (v33 & 0x8000000000000000uLL) != 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v33, v28, v29, v30, v31, v32, v52);
    sub_1440("AutoGen.c", 427, "!EFI_ERROR (Status)");
  }
  v39 = sub_2FA0();
  if ( v39 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v39, v34, v35, v36, v37, v38, v52);
    sub_1440("AutoGen.c", 430, "!EFI_ERROR (Status)");
  }
  v45 = sub_3044();
  if ( (v45 & 0x8000000000000000uLL) != 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v45, v40, v41, v42, v43, v44, v52);
    sub_1440("AutoGen.c", 433, "!EFI_ERROR (Status)");
  }
  v51 = sub_31E4();
  if ( v51 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v51, v46, v47, v48, v49, v50, v52);
    sub_1440("AutoGen.c", 436, "!EFI_ERROR (Status)");
  }
}
// 1FA4: variable 'v4' is possibly undefined
// 1FA4: variable 'v5' is possibly undefined
// 1FA4: variable 'v6' is possibly undefined
// 1FA4: variable 'v7' is possibly undefined
// 1FA4: variable 'v8' is possibly undefined
// 1FA4: variable 'v52' is possibly undefined
// 1FE4: variable 'v10' is possibly undefined
// 1FE4: variable 'v11' is possibly undefined
// 1FE4: variable 'v12' is possibly undefined
// 1FE4: variable 'v13' is possibly undefined
// 1FE4: variable 'v14' is possibly undefined
// 2024: variable 'v16' is possibly undefined
// 2024: variable 'v17' is possibly undefined
// 2024: variable 'v18' is possibly undefined
// 2024: variable 'v19' is possibly undefined
// 2024: variable 'v20' is possibly undefined
// 2064: variable 'v22' is possibly undefined
// 2064: variable 'v23' is possibly undefined
// 2064: variable 'v24' is possibly undefined
// 2064: variable 'v25' is possibly undefined
// 2064: variable 'v26' is possibly undefined
// 20A4: variable 'v28' is possibly undefined
// 20A4: variable 'v29' is possibly undefined
// 20A4: variable 'v30' is possibly undefined
// 20A4: variable 'v31' is possibly undefined
// 20A4: variable 'v32' is possibly undefined
// 20DC: variable 'v34' is possibly undefined
// 20DC: variable 'v35' is possibly undefined
// 20DC: variable 'v36' is possibly undefined
// 20DC: variable 'v37' is possibly undefined
// 20DC: variable 'v38' is possibly undefined
// 211C: variable 'v40' is possibly undefined
// 211C: variable 'v41' is possibly undefined
// 211C: variable 'v42' is possibly undefined
// 211C: variable 'v43' is possibly undefined
// 211C: variable 'v44' is possibly undefined
// 2160: variable 'v46' is possibly undefined
// 2160: variable 'v47' is possibly undefined
// 2160: variable 'v48' is possibly undefined
// 2160: variable 'v49' is possibly undefined
// 2160: variable 'v50' is possibly undefined
// 2DEC: using guessed type __int64 __fastcall sub_2DEC(_QWORD, _QWORD);

//----- (000000000000218C) ----------------------------------------------------
__int64 sub_218C()
{
  return 0;
}

//----- (0000000000002194) ----------------------------------------------------
__int64 __fastcall sub_2194(__int64 a1)
{
  __int64 (__fastcall *v1)(__int64 *, void *, void *, _QWORD); // x9
  __int64 result; // x0
  __int64 v3; // x1
  __int64 v4; // x2
  __int64 v5; // x3
  __int64 v6; // x4
  __int64 v7; // x5
  __int64 v8; // x6
  __int64 v9; // x7
  __int64 v10; // [xsp+0h] [xbp-10h] BYREF
  __int64 v11; // [xsp+8h] [xbp-8h]

  v11 = qword_5000;
  v1 = (__int64 (__fastcall *)(__int64 *, void *, void *, _QWORD))*((_QWORD *)off_5188 + 41);
  v10 = a1;
  result = v1(&v10, &unk_5070, &unk_50E0, 0);
  if ( qword_5000 != v11 )
  {
    sub_104C(result, v3, v4, v5, v6, v7, v8, v9, v10);
    return sub_21FC();
  }
  return result;
}
// 21F8: variable 'v3' is possibly undefined
// 21F8: variable 'v4' is possibly undefined
// 21F8: variable 'v5' is possibly undefined
// 21F8: variable 'v6' is possibly undefined
// 21F8: variable 'v7' is possibly undefined
// 21F8: variable 'v8' is possibly undefined
// 21F8: variable 'v9' is possibly undefined
// 21FC: using guessed type __int64 sub_21FC(void);
// 5000: using guessed type __int64 qword_5000;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (00000000000021FC) ----------------------------------------------------
__int64 __fastcall sub_21FC(
        _BYTE *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8)
{
  __int64 v9; // x0
  __int64 result; // x0
  __int64 (__fastcall **v12)(_BYTE *); // x8
  __int64 v13; // x8
  __int64 (__fastcall **v14)(_BYTE *); // x9
  __int64 v15; // x9
  int v16; // [xsp+0h] [xbp-20h] BYREF
  _BYTE v17[4]; // [xsp+4h] [xbp-1Ch] BYREF
  __int64 v18; // [xsp+8h] [xbp-18h]

  v18 = qword_5000;
  v17[0] = 0;
  if ( a1 )
  {
    sub_2B18((__int64)&v16, a2, a3, a4, a5, a6, a7, a8);
    if ( v9 )
    {
      result = 0x8000000000000007uLL;
    }
    else if ( v16 == 1 || v16 == 15 )
    {
      result = 0x8000000000000003uLL;
    }
    else
    {
      v12 = (__int64 (__fastcall **)(_BYTE *))off_5160;
      if ( off_5160
        || (v13 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_5080, 0, &off_5160),
            result = 0x8000000000000007uLL,
            !v13)
        && (v12 = (__int64 (__fastcall **)(_BYTE *))off_5160) != 0 )
      {
        result = v12[11](a1);
        if ( !result )
        {
          v14 = (__int64 (__fastcall **)(_BYTE *))off_5168;
          if ( off_5168
            || (v15 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_5090, 0, &off_5168),
                result = 0x8000000000000007uLL,
                !v15)
            && (v14 = (__int64 (__fastcall **)(_BYTE *))off_5168) != 0 )
          {
            result = v14[15](v17);
            if ( !result )
              *a1 |= v17[0];
          }
        }
      }
    }
  }
  else
  {
    result = 0x8000000000000002uLL;
  }
  if ( qword_5000 != v18 )
  {
    sub_104C(result, a2, a3, a4, a5, a6, a7, a8, v16);
    return sub_2340();
  }
  return result;
}
// 222C: variable 'v9' is possibly undefined
// 233C: variable 'a2' is possibly undefined
// 233C: variable 'a3' is possibly undefined
// 233C: variable 'a4' is possibly undefined
// 233C: variable 'a5' is possibly undefined
// 233C: variable 'a6' is possibly undefined
// 233C: variable 'a7' is possibly undefined
// 233C: variable 'a8' is possibly undefined
// 2340: using guessed type __int64 sub_2340(void);
// 5000: using guessed type __int64 qword_5000;
// 5160: using guessed type _UNKNOWN *off_5160;
// 5168: using guessed type _UNKNOWN *off_5168;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002340) ----------------------------------------------------
__int64 __fastcall sub_2340(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8)
{
  __int64 v9; // x0
  __int64 result; // x0
  __int64 (__fastcall **v12)(_QWORD); // x8
  __int64 v13; // x8
  char v14; // [xsp+0h] [xbp-20h]
  int v15; // [xsp+4h] [xbp-1Ch] BYREF
  __int64 v16; // [xsp+8h] [xbp-18h]

  v16 = qword_5000;
  if ( a1 )
  {
    sub_2B18((__int64)&v15, a2, a3, a4, a5, a6, a7, a8);
    if ( v9 )
    {
      result = 0x8000000000000007uLL;
    }
    else if ( v15 == 1 || v15 == 15 )
    {
      result = 0x8000000000000003uLL;
    }
    else
    {
      v12 = (__int64 (__fastcall **)(_QWORD))off_5168;
      if ( off_5168
        || (v13 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_5090, 0, &off_5168),
            result = 0x8000000000000007uLL,
            !v13)
        && (v12 = (__int64 (__fastcall **)(_QWORD))off_5168) != 0 )
      {
        result = v12[10](a1);
      }
    }
  }
  else
  {
    result = 0x8000000000000002uLL;
  }
  if ( qword_5000 != v16 )
  {
    sub_104C(result, a2, a3, a4, a5, a6, a7, a8, v14);
    return sub_2414();
  }
  return result;
}
// 236C: variable 'v9' is possibly undefined
// 2410: variable 'a2' is possibly undefined
// 2410: variable 'a3' is possibly undefined
// 2410: variable 'a4' is possibly undefined
// 2410: variable 'a5' is possibly undefined
// 2410: variable 'a6' is possibly undefined
// 2410: variable 'a7' is possibly undefined
// 2410: variable 'a8' is possibly undefined
// 2410: variable 'v14' is possibly undefined
// 2414: using guessed type __int64 sub_2414(void);
// 5000: using guessed type __int64 qword_5000;
// 5168: using guessed type _UNKNOWN *off_5168;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002414) ----------------------------------------------------
_DWORD *__fastcall sub_2414(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8)
{
  __int64 v8; // x20
  __int64 *v9; // x21
  __int64 v11; // x0
  _DWORD *result; // x0
  __int64 (__fastcall **v14)(_QWORD); // x8
  __int64 v15; // x8
  __int64 v16; // x1
  __int64 v17; // x2
  __int64 v18; // x3
  __int64 v19; // x4
  __int64 v20; // x5
  __int64 v21; // x6
  __int64 v22; // x7
  __int64 v23; // x30
  _BYTE *v24; // x0
  _BYTE *v25; // x19
  __int64 v26; // x0
  __int64 v28; // x8
  __int64 v29; // x20
  __int64 v30; // x20
  __int64 v31; // x1
  __int64 v32; // x2
  __int64 v33; // x3
  __int64 v34; // x4
  __int64 v35; // x5
  __int64 v36; // x6
  __int64 v37; // x7
  __int64 v38; // x1
  __int64 v39; // x2
  __int64 v40; // x3
  __int64 v41; // x4
  __int64 v42; // x5
  __int64 v43; // x6
  __int64 v44; // x7
  __int64 v45; // x30
  __int64 v46; // x19
  int v47; // w0
  int v48; // w20
  __int64 v49; // x0
  __int64 v51; // x20
  __int64 v52; // x1
  __int64 v53; // x2
  __int64 v54; // x3
  __int64 v55; // x4
  __int64 v56; // x5
  __int64 v57; // x6
  __int64 v58; // x7
  __int64 v59; // x20
  __int64 v60; // x20
  __int64 (__fastcall **v61)(_QWORD, int *); // x8
  __int64 v62; // x10
  unsigned int v63; // w8
  int v64; // w11
  char v65; // [xsp+0h] [xbp-C0h]
  int v66; // [xsp+4h] [xbp-BCh] BYREF
  _BYTE v67[4]; // [xsp+8h] [xbp-B8h] BYREF
  _BYTE v68[4]; // [xsp+Ch] [xbp-B4h] BYREF
  unsigned int v69; // [xsp+10h] [xbp-B0h] BYREF
  unsigned int v70; // [xsp+14h] [xbp-ACh] BYREF
  __int64 v71; // [xsp+18h] [xbp-A8h]
  __int64 *v72; // [xsp+20h] [xbp-A0h]
  __int64 v73; // [xsp+30h] [xbp-90h]
  _BYTE *v74; // [xsp+38h] [xbp-88h]
  _QWORD *v75; // [xsp+40h] [xbp-80h]
  __int64 v76; // [xsp+48h] [xbp-78h]
  int v77; // [xsp+50h] [xbp-70h] BYREF
  _BYTE v78[4]; // [xsp+54h] [xbp-6Ch] BYREF
  _BYTE v79[4]; // [xsp+58h] [xbp-68h] BYREF
  _BYTE v80[4]; // [xsp+5Ch] [xbp-64h] BYREF
  _BYTE v81[8]; // [xsp+60h] [xbp-60h] BYREF
  __int64 v82; // [xsp+68h] [xbp-58h]
  __int64 *v83; // [xsp+70h] [xbp-50h]
  __int64 v84; // [xsp+80h] [xbp-40h]
  __int64 v85; // [xsp+88h] [xbp-38h]
  _QWORD v86[2]; // [xsp+90h] [xbp-30h] BYREF
  char v87; // [xsp+A0h] [xbp-20h]
  int v88; // [xsp+A4h] [xbp-1Ch] BYREF
  __int64 v89; // [xsp+A8h] [xbp-18h]
  __int64 vars0; // [xsp+C0h] [xbp+0h] BYREF

  v89 = qword_5000;
  if ( a1 )
  {
    sub_2B18((__int64)&v88, a2, a3, a4, a5, a6, a7, a8);
    if ( v11 )
    {
      result = (_DWORD *)0x8000000000000007LL;
    }
    else if ( v88 == 1 || v88 == 15 )
    {
      result = (_DWORD *)0x8000000000000003LL;
    }
    else
    {
      v8 = (__int64)&off_5160;
      v14 = (__int64 (__fastcall **)(_QWORD))off_5168;
      if ( off_5168
        || (v15 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_5090, 0, &off_5168),
            result = (_DWORD *)0x8000000000000007LL,
            !v15)
        && (v14 = (__int64 (__fastcall **)(_QWORD))off_5168) != 0 )
      {
        result = (_DWORD *)v14[11](a1);
      }
    }
  }
  else
  {
    result = (_DWORD *)0x8000000000000002LL;
  }
  if ( qword_5000 != v89 )
  {
    sub_104C((__int64)result, a2, a3, a4, a5, a6, a7, a8, v87);
    v83 = v9;
    v84 = v8;
    v85 = a1;
    v86[0] = &vars0;
    v86[1] = v23;
    v25 = v24;
    v82 = qword_5000;
    v80[0] = 0;
    v79[0] = 0;
    v78[0] = 0;
    if ( v24 )
    {
      sub_2B18((__int64)&v77, v16, v17, v18, v19, v20, v21, v22);
      if ( v26 )
      {
        result = (_DWORD *)0x8000000000000007LL;
      }
      else if ( v77 == 1 || v77 == 15 )
      {
        result = (_DWORD *)0x8000000000000003LL;
      }
      else
      {
        v9 = &qword_5000;
        if ( off_5158
          || (v8 = (__int64)&off_5158,
              v28 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_50A0, 0, &off_5158),
              result = (_DWORD *)0x8000000000000007LL,
              !v28)
          && off_5158 )
        {
          v29 = sub_2340((__int64)v78, v16, v17, v18, v19, v20, v21, v22);
          v30 = v29 | (*((__int64 (__fastcall **)(_QWORD, _BYTE *))off_5158 + 6))(0, v81);
          v8 = v30 | (*((__int64 (__fastcall **)(_QWORD, _BYTE *))off_5158 + 7))(0, v79);
          result = (_DWORD *)(v8 | sub_21FC(v80, v31, v32, v33, v34, v35, v36, v37));
          if ( !result )
          {
            if ( !v79[0] && v78[0] && v80[0] && (v81[0] & 0x81) == 0 && (v81[0] & 0x30) != 0 )
            {
              result = 0;
              *v25 = 1;
            }
            else
            {
              result = 0;
              *v25 = 0;
            }
          }
        }
      }
    }
    else
    {
      result = (_DWORD *)0x8000000000000002LL;
    }
    if ( qword_5000 != v82 )
    {
      sub_104C((__int64)result, v16, v17, v18, v19, v20, v21, v22, v77);
      v72 = v9;
      v73 = v8;
      v74 = v25;
      v75 = v86;
      v76 = v45;
      v46 = v38;
      v48 = v47;
      v71 = qword_5000;
      v69 = 0;
      v70 = 0;
      v68[0] = 0;
      v67[0] = 0;
      if ( v38 )
      {
        sub_2B18((__int64)&v66, v38, v39, v40, v41, v42, v43, v44);
        if ( v49 )
        {
          result = (_DWORD *)0x8000000000000007LL;
        }
        else if ( v66 == 1 || v66 == 15 )
        {
          result = (_DWORD *)0x8000000000000003LL;
        }
        else if ( v48 )
        {
          result = 0;
        }
        else
        {
          v51 = sub_2340((__int64)v68, v38, v39, v40, v41, v42, v43, v44);
          v59 = sub_21FC(v67, v52, v53, v54, v55, v56, v57, v58) | v51;
          v60 = v59 | sub_2414(&v69);
          if ( !v60 )
            *(_DWORD *)(v46 + 4) = v69;
          v61 = (__int64 (__fastcall **)(_QWORD, int *))off_5168;
          if ( off_5168
            || (v62 = (*((__int64 (__fastcall **)(void *, _QWORD, _UNKNOWN **))off_5188 + 40))(&unk_5090, 0, &off_5168)
                    | v60,
                result = (_DWORD *)0x8000000000000007LL,
                !v62)
            && (v61 = (__int64 (__fastcall **)(_QWORD, int *))off_5168, v60 = 0, off_5168) )
          {
            result = (_DWORD *)(v61[16](0, (int *)&v70) | v60);
            if ( !result )
            {
              v63 = v70;
              v64 = v68[0];
              *(_DWORD *)(v46 + 8) = v70;
              if ( v64 && v69 <= v63 )
              {
                result = 0;
                *(_BYTE *)v46 = 0;
              }
              else
              {
                result = 0;
                *(_BYTE *)v46 = 1;
              }
            }
          }
        }
      }
      else
      {
        result = (_DWORD *)0x8000000000000002LL;
      }
      if ( qword_5000 != v71 )
      {
        sub_104C((__int64)result, v38, v39, v40, v41, v42, v43, v44, v65);
        return sub_27C8();
      }
    }
  }
  return result;
}
// 2440: variable 'v11' is possibly undefined
// 24E4: variable 'a2' is possibly undefined
// 24E4: variable 'a3' is possibly undefined
// 24E4: variable 'a4' is possibly undefined
// 24E4: variable 'a5' is possibly undefined
// 24E4: variable 'a6' is possibly undefined
// 24E4: variable 'a7' is possibly undefined
// 24E4: variable 'a8' is possibly undefined
// 24EC: variable 'v9' is possibly undefined
// 24F0: variable 'v8' is possibly undefined
// 24F4: variable 'v23' is possibly undefined
// 2500: variable 'v24' is possibly undefined
// 2520: variable 'v16' is possibly undefined
// 2520: variable 'v17' is possibly undefined
// 2520: variable 'v18' is possibly undefined
// 2520: variable 'v19' is possibly undefined
// 2520: variable 'v20' is possibly undefined
// 2520: variable 'v21' is possibly undefined
// 2520: variable 'v22' is possibly undefined
// 2524: variable 'v26' is possibly undefined
// 25DC: variable 'v31' is possibly undefined
// 25DC: variable 'v32' is possibly undefined
// 25DC: variable 'v33' is possibly undefined
// 25DC: variable 'v34' is possibly undefined
// 25DC: variable 'v35' is possibly undefined
// 25DC: variable 'v36' is possibly undefined
// 25DC: variable 'v37' is possibly undefined
// 2668: variable 'v45' is possibly undefined
// 2674: variable 'v38' is possibly undefined
// 2678: variable 'v47' is possibly undefined
// 2698: variable 'v39' is possibly undefined
// 2698: variable 'v40' is possibly undefined
// 2698: variable 'v41' is possibly undefined
// 2698: variable 'v42' is possibly undefined
// 2698: variable 'v43' is possibly undefined
// 2698: variable 'v44' is possibly undefined
// 269C: variable 'v49' is possibly undefined
// 26E8: variable 'v52' is possibly undefined
// 26E8: variable 'v53' is possibly undefined
// 26E8: variable 'v54' is possibly undefined
// 26E8: variable 'v55' is possibly undefined
// 26E8: variable 'v56' is possibly undefined
// 26E8: variable 'v57' is possibly undefined
// 26E8: variable 'v58' is possibly undefined
// 27C4: variable 'v65' is possibly undefined
// 5000: using guessed type __int64 qword_5000;
// 5158: using guessed type _UNKNOWN *off_5158;
// 5160: using guessed type _UNKNOWN *off_5160;
// 5168: using guessed type _UNKNOWN *off_5168;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (00000000000027C8) ----------------------------------------------------
_DWORD *sub_27C8()
{
  _DWORD *result; // x0

  result = sub_31BC(qword_5020);
  if ( result )
    return (_DWORD *)*((_QWORD *)result + 3);
  return result;
}
// 5020: using guessed type _QWORD qword_5020[2];

//----- (00000000000027EC) ----------------------------------------------------
__int64 sub_27EC()
{
  return 2147484672LL;
}

//----- (00000000000027F8) ----------------------------------------------------
void sub_27F8()
{
  __int64 (__fastcall *v0)(void *, _QWORD, __int64 *); // x8

  if ( !qword_5170 )
  {
    if ( off_5188 )
    {
      v0 = (__int64 (__fastcall *)(void *, _QWORD, __int64 *))*((_QWORD *)off_5188 + 40);
      if ( v0 )
      {
        if ( v0(&unk_50C0, 0, &qword_5170) < 0 )
          qword_5170 = 0;
      }
    }
  }
}
// 5170: using guessed type __int64 qword_5170;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002850) ----------------------------------------------------
__int64 __fastcall sub_2850(unsigned int a1, unsigned int a2, unsigned int a3, __int64 a4, __int64 a5)
{
  if ( ((unsigned __int8)a1 == 2 || (unsigned __int8)a1 == 3) && (sub_27F8(), qword_5170) )
    return (*(__int64 (__fastcall **)(_QWORD, _QWORD, _QWORD, __int64, __int64))qword_5170)(a1, a2, a3, a4, a5);
  else
    return 0x8000000000000003uLL;
}
// 5170: using guessed type __int64 qword_5170;

//----- (00000000000028FC) ----------------------------------------------------
__int64 sub_28FC()
{
  return 0;
}

//----- (000000000000290C) ----------------------------------------------------
__int64 sub_290C()
{
  return 1;
}

//----- (000000000000291C) ----------------------------------------------------
__int64 sub_291C()
{
  return 1;
}

//----- (000000000000292C) ----------------------------------------------------
__int64 __fastcall sub_292C(
        unsigned int a1,
        unsigned int a2,
        unsigned int a3,
        void *a4,
        void *a5,
        __int64 a6,
        unsigned __int64 a7)
{
  unsigned __int64 v14; // x26
  _BYTE *v15; // x8
  __int64 v16; // x24
  void *v18; // x1
  void *v19; // x3
  __int64 v20; // x0
  _BYTE *v21; // [xsp+8h] [xbp-268h] BYREF
  _BYTE v22[520]; // [xsp+10h] [xbp-260h] BYREF
  __int64 v23; // [xsp+218h] [xbp-58h]

  v23 = qword_5000;
  if ( !a6 && a7 )
  {
    sub_1440("ReportStatusCodeLib.c", 496, "!((ExtendedData == ((void *) 0)) && (ExtendedDataSize != 0))");
    while ( 1 )
      ;
  }
  if ( a6 && !a7 )
  {
    sub_1440("ReportStatusCodeLib.c", 497, "!((ExtendedData != ((void *) 0)) && (ExtendedDataSize == 0))");
    while ( 1 )
      ;
  }
  if ( off_5188 && *((_QWORD *)off_5188 + 8) && *((_QWORD *)off_5188 + 9) )
  {
    v14 = (*((__int64 (__fastcall **)(__int64))off_5188 + 3))(31);
    (*((void (**)(void))off_5188 + 4))();
    v21 = 0;
    if ( v14 > 0x10
      || ((*((void (__fastcall **)(__int64, unsigned __int64, _BYTE **))off_5188 + 8))(4, a7 + 20, &v21),
          (v15 = v21) == 0) )
    {
      if ( a7 >= 0x1ED )
      {
        sub_10AC(0x80000000LL, "Status code extended data is too large to be reported!\n");
        v16 = 0x8000000000000009uLL;
        goto LABEL_17;
      }
      v15 = v22;
      v21 = v22;
    }
    *(_WORD *)v15 = 20;
    if ( a5 )
      v18 = a5;
    else
      v18 = &unk_5030;
    *((_WORD *)v21 + 1) = a7;
    sub_2BBC((__int64)(v21 + 4), (__int64)v18);
    if ( a6 )
      sub_1904((__int64)(v21 + 20), a6, a7);
    if ( a4 )
      v19 = a4;
    else
      v19 = &unk_5008;
    v16 = sub_2850(a1, a2, a3, (__int64)v19, (__int64)v21);
    if ( v21 != v22 )
      (*((void (**)(void))off_5188 + 9))();
  }
  else
  {
    v16 = 0x8000000000000003uLL;
  }
LABEL_17:
  if ( qword_5000 == v23 )
    return v16;
  v20 = sub_104C();
  return sub_2B18(v20);
}
// 104C: using guessed type __int64 sub_104C(void);
// 10AC: using guessed type __int64 __fastcall sub_10AC(_QWORD, _QWORD);
// 1440: using guessed type __int64 __fastcall sub_1440(_QWORD, _QWORD, _QWORD);
// 2B18: using guessed type __int64 __fastcall sub_2B18(_QWORD);
// 5000: using guessed type __int64 qword_5000;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002B18) ----------------------------------------------------
void __fastcall sub_2B18(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8)
{
  _DWORD *v8; // x19
  __int64 v9; // x0
  __int64 v10; // x1
  _DWORD v11[4]; // [xsp+0h] [xbp-30h] BYREF
  __int64 v12; // [xsp+10h] [xbp-20h] BYREF
  __int64 v13; // [xsp+18h] [xbp-18h]

  v8 = (_DWORD *)a1;
  v13 = qword_5000;
  if ( a1 )
  {
    a1 = (*((__int64 (__fastcall **)(void *, _QWORD, __int64 *))off_5188 + 40))(&unk_50D0, 0, &v12);
    if ( !a1 )
    {
      a1 = (*(__int64 (__fastcall **)(__int64, _DWORD *))(v12 + 8))(v12, v11);
      if ( !a1 )
        *v8 = v11[0];
    }
  }
  if ( qword_5000 != v13 )
  {
    sub_104C(a1, a2, a3, a4, a5, a6, a7, a8, v11[0]);
    sub_2BBC(v9, v10);
  }
}
// 2BB8: variable 'a2' is possibly undefined
// 2BB8: variable 'a3' is possibly undefined
// 2BB8: variable 'a4' is possibly undefined
// 2BB8: variable 'a5' is possibly undefined
// 2BB8: variable 'a6' is possibly undefined
// 2BB8: variable 'a7' is possibly undefined
// 2BB8: variable 'a8' is possibly undefined
// 2BB9: variable 'v9' is possibly undefined
// 2BB9: variable 'v10' is possibly undefined
// 5000: using guessed type __int64 qword_5000;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002BBC) ----------------------------------------------------
void __fastcall sub_2BBC(__int64 a1, __int64 a2)
{
  if ( a1 )
  {
    if ( a2 )
      JUMPOUT(0x1CEC);
    sub_1440("MemLibGuid.c", 48, "SourceGuid != ((void *) 0)");
    while ( 1 )
      ;
  }
  sub_1440("MemLibGuid.c", 47, "DestinationGuid != ((void *) 0)");
  while ( 1 )
    ;
}
// 2BD4: control flows out of bounds to 1CEC
// 1440: using guessed type __int64 __fastcall sub_1440(_QWORD, _QWORD, _QWORD);

//----- (0000000000002C10) ----------------------------------------------------
bool __fastcall sub_2C10(_QWORD *a1, _QWORD *a2)
{
  if ( !a1 )
  {
    sub_1440("MemLibGuid.c", 76, "Guid1 != ((void *) 0)");
    while ( 1 )
      ;
  }
  if ( !a2 )
  {
    sub_1440("MemLibGuid.c", 77, "Guid2 != ((void *) 0)");
    while ( 1 )
      ;
  }
  return *a2 == *a1 && a2[1] == a1[1];
}
// 2C68: conditional instruction was optimized away because x1.8!=0

//----- (0000000000002C80) ----------------------------------------------------
__int64 __fastcall sub_2C80(__int64 a1, __int64 a2)
{
  qword_5178 = a1;
  if ( !a1 )
  {
    sub_1440("UefiBootServicesTableLib.c", 51, "gImageHandle != ((void *) 0)");
    while ( 1 )
      ;
  }
  qword_5180 = a2;
  if ( !a2 )
  {
    sub_1440("UefiBootServicesTableLib.c", 57, "gST != ((void *) 0)");
    while ( 1 )
      ;
  }
  off_5188 = *(_UNKNOWN **)(a2 + 96);
  if ( !off_5188 )
  {
    sub_1440("UefiBootServicesTableLib.c", 63, "gBS != ((void *) 0)");
    while ( 1 )
      ;
  }
  return 0;
}
// 5178: using guessed type __int64 qword_5178;
// 5180: using guessed type __int64 qword_5180;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (0000000000002D10) ----------------------------------------------------
unsigned __int64 sub_2D10()
{
  unsigned __int64 v0; // x19

  qword_5198 = sub_36A8(16LL * (unsigned int)dword_5190, 16LL * (unsigned int)(dword_5190 + 16), qword_5198);
  if ( qword_5198 )
  {
    qword_51A0 = sub_36A8(8LL * (unsigned int)dword_5190, 8LL * (unsigned int)(dword_5190 + 16), qword_51A0);
    if ( qword_51A0 )
    {
      qword_51A8 = sub_36A8(8LL * (unsigned int)dword_5190, 8LL * (unsigned int)(dword_5190 + 16), qword_51A8);
      if ( qword_51A8 )
      {
        v0 = 0;
        dword_5190 += 16;
        return v0;
      }
    }
    if ( qword_5198 )
      sub_3650();
  }
  if ( qword_51A0 )
    sub_3650();
  v0 = 0x8000000000000009uLL;
  if ( qword_51A8 )
    sub_3650();
  return v0;
}
// 5190: using guessed type int dword_5190;
// 5198: using guessed type __int64 qword_5198;
// 51A0: using guessed type __int64 qword_51A0;
// 51A8: using guessed type __int64 qword_51A8;

//----- (0000000000002DF0) ----------------------------------------------------
__int64 __fastcall sub_2DF0(__int64 a1, __int64 a2)
{
  qword_51B0 = *(_QWORD *)(a2 + 88);
  if ( !qword_51B0 )
  {
    sub_1440("UefiRuntimeServicesTableLib.c", 47, "gRT != ((void *) 0)");
    while ( 1 )
      ;
  }
  return 0;
}
// 51B0: using guessed type __int64 qword_51B0;

//----- (0000000000002E30) ----------------------------------------------------
__int64 sub_2E30()
{
  return 0;
}

//----- (0000000000002E38) ----------------------------------------------------
unsigned __int64 __fastcall sub_2E38(_QWORD *a1, _QWORD *a2)
{
  unsigned __int64 v4; // x22
  __int64 v5; // x21
  __int64 v6; // x25
  __int64 v7; // x24
  unsigned __int64 result; // x0

  if ( !a1 )
  {
    sub_1440("UefiLib.c", 97, "TableGuid != ((void *) 0)");
    while ( 1 )
      ;
  }
  if ( !a2 )
  {
    sub_1440("UefiLib.c", 98, "Table != ((void *) 0)");
    while ( 1 )
      ;
  }
  v4 = -1;
  v5 = qword_5180;
  v6 = 16;
  *a2 = 0;
  while ( 1 )
  {
    v7 = v6;
    ++v4;
    result = 0x800000000000000EuLL;
    if ( v4 >= *(_QWORD *)(v5 + 104) )
      break;
    v6 += 24;
    if ( sub_2C10(a1, (_QWORD *)(*(_QWORD *)(v5 + 112) + v7 - 16)) )
    {
      result = 0;
      *a2 = *(_QWORD *)(*(_QWORD *)(v5 + 112) + v7);
      return result;
    }
  }
  return result;
}
// 5180: using guessed type __int64 qword_5180;

//----- (0000000000002F14) ----------------------------------------------------
unsigned __int64 sub_2F14()
{
  __int64 v0; // x3
  __int64 v1; // x4
  __int64 v2; // x5
  __int64 v3; // x6
  __int64 v4; // x7
  unsigned __int64 v5; // x19
  char v7; // [xsp+0h] [xbp-10h]

  v5 = sub_2E38(qword_5050, &qword_51B8);
  if ( (v5 & 0x8000000000000000uLL) != 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v5, v0, v1, v2, v3, v4, v7);
    sub_1440("DxeServicesTableLib.c", 64, "!EFI_ERROR (Status)");
  }
  if ( !qword_51B8 )
  {
    sub_1440("DxeServicesTableLib.c", 65, "gDS != ((void *) 0)");
    while ( 1 )
      ;
  }
  return v5;
}
// 2F4C: variable 'v0' is possibly undefined
// 2F4C: variable 'v1' is possibly undefined
// 2F4C: variable 'v2' is possibly undefined
// 2F4C: variable 'v3' is possibly undefined
// 2F4C: variable 'v4' is possibly undefined
// 2F4C: variable 'v7' is possibly undefined
// 5050: using guessed type _QWORD qword_5050[2];
// 51B8: using guessed type __int64 qword_51B8;

//----- (0000000000002FA0) ----------------------------------------------------
__int64 sub_2FA0()
{
  __int64 v0; // x0
  __int64 v1; // x1
  __int64 v2; // x2
  __int64 v3; // x3
  __int64 v4; // x4
  __int64 v5; // x5
  __int64 v6; // x6
  __int64 v7; // x7
  __int64 v8; // x0
  char vars0; // [xsp+0h] [xbp+0h]

  v0 = sub_3528();
  if ( !v0 )
  {
    sub_10AC(
      0x80000000,
      "ARM Architectural Timer is not available in the CPU, hence this library cannot be used.\n",
      v2,
      v3,
      v4,
      v5,
      v6,
      v7,
      vars0);
    sub_1440("ArmArchTimerLib.c", 80, "0");
    while ( 1 )
      ;
  }
  sub_36C8(v0, v1, v2, v3, v4, v5, v6, v7, vars0);
  if ( !v8 )
  {
    sub_1440("ArmArchTimerLib.c", 76, "ArmGenericTimerGetTimerFreq () != 0");
    while ( 1 )
      ;
  }
  return 0;
}
// 2FCC: variable 'v1' is possibly undefined
// 2FCC: variable 'v2' is possibly undefined
// 2FCC: variable 'v3' is possibly undefined
// 2FCC: variable 'v4' is possibly undefined
// 2FCC: variable 'v5' is possibly undefined
// 2FCC: variable 'v6' is possibly undefined
// 2FCC: variable 'v7' is possibly undefined
// 2FCC: variable 'vars0' is possibly undefined
// 2FD0: variable 'v8' is possibly undefined

//----- (0000000000003044) ----------------------------------------------------
unsigned __int64 sub_3044()
{
  __int64 v0; // x3
  __int64 v1; // x4
  __int64 v2; // x5
  __int64 v3; // x6
  __int64 v4; // x7
  unsigned __int64 v5; // x19
  char v7; // [xsp+0h] [xbp-10h]

  v5 = sub_2E38(qword_5060, &qword_51C0);
  if ( (v5 & 0x8000000000000000uLL) != 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v5, v0, v1, v2, v3, v4, v7);
    sub_1440("HobLib.c", 49, "!EFI_ERROR (Status)");
  }
  if ( !qword_51C0 )
  {
    sub_1440("HobLib.c", 50, "mHobList != ((void *) 0)");
    while ( 1 )
      ;
  }
  return v5;
}
// 307C: variable 'v0' is possibly undefined
// 307C: variable 'v1' is possibly undefined
// 307C: variable 'v2' is possibly undefined
// 307C: variable 'v3' is possibly undefined
// 307C: variable 'v4' is possibly undefined
// 307C: variable 'v7' is possibly undefined
// 5060: using guessed type _QWORD qword_5060[2];
// 51C0: using guessed type __int64 qword_51C0;

//----- (00000000000030D0) ----------------------------------------------------
__int64 sub_30D0()
{
  __int64 result; // x0

  result = qword_51C0;
  if ( !qword_51C0 )
  {
    sub_1440("HobLib.c", 77, "mHobList != ((void *) 0)");
    while ( 1 )
      ;
  }
  return result;
}
// 51C0: using guessed type __int64 qword_51C0;

//----- (0000000000003108) ----------------------------------------------------
_DWORD *__fastcall sub_3108(unsigned __int16 a1, _DWORD *a2)
{
  int v2; // w9

  if ( !a2 )
  {
    sub_1440("HobLib.c", 107, "HobStart != ((void *) 0)");
    while ( 1 )
      ;
  }
  while ( 1 )
  {
    v2 = (unsigned __int16)*a2;
    if ( v2 == 0xFFFF )
      break;
    if ( v2 == a1 )
      return a2;
    a2 = (_DWORD *)((char *)a2 + HIWORD(*a2));
  }
  return 0;
}

//----- (000000000000316C) ----------------------------------------------------
_DWORD *__fastcall sub_316C(_QWORD *a1, _DWORD *a2)
{
  _DWORD *v3; // x0
  _DWORD *v4; // x20

  while ( 1 )
  {
    v3 = sub_3108(4u, a2);
    v4 = v3;
    if ( !v3 || sub_2C10(a1, (_QWORD *)v3 + 1) )
      break;
    a2 = (_DWORD *)((char *)v4 + *((unsigned __int16 *)v4 + 1));
  }
  return v4;
}

//----- (00000000000031BC) ----------------------------------------------------
_DWORD *__fastcall sub_31BC(_QWORD *a1)
{
  _DWORD *v2; // x1

  v2 = (_DWORD *)sub_30D0();
  return sub_316C(a1, v2);
}

//----- (00000000000031E4) ----------------------------------------------------
__int64 sub_31E4()
{
  sub_34A8((__int64)sub_320C, 264);
  return 0;
}

//----- (000000000000320C) ----------------------------------------------------
_QWORD *__fastcall sub_320C(_QWORD *result, __int64 a2)
{
  unsigned __int64 StatusReg; // x2
  __int64 v8; // x3
  unsigned __int64 v9; // x8
  unsigned __int64 v10; // x8
  unsigned __int64 v11; // x8

  StatusReg = _ReadStatusReg(DAIF);
  __asm { MSR             DAIFSet, #0xF }
  __isb(0xFu);
  __asm { DC              CIVAC, X0 }
  __dsb(0xBu);
  v8 = _ReadStatusReg(CurrentEL);
  if ( v8 > 8 )
  {
    v11 = _ReadStatusReg(SCTLR_EL3);
    _WriteStatusReg(SCTLR_EL3, v11 & 0xFFFFFFFFFFFFEFFAuLL);
    __isb(0xFu);
    *result = a2;
    __dmb(0xFu);
    __dsb(0xFu);
    __asm { DC              IVAC, X0 }
    __isb(0xFu);
    __asm { TLBI            ALLE3 }
    __dsb(0xFu);
    __isb(0xFu);
    _WriteStatusReg(SCTLR_EL3, v11 | 0x1005);
    __isb(0xFu);
  }
  else if ( v8 == 8 )
  {
    v10 = _ReadStatusReg(SCTLR_EL2);
    _WriteStatusReg(SCTLR_EL2, v10 & 0xFFFFFFFFFFFFEFFAuLL);
    __isb(0xFu);
    *result = a2;
    __dmb(0xFu);
    __dsb(0xFu);
    __asm { DC              IVAC, X0 }
    __isb(0xFu);
    __asm { TLBI            ALLE2 }
    __dsb(0xFu);
    __isb(0xFu);
    _WriteStatusReg(SCTLR_EL2, v10 | 0x1005);
    __isb(0xFu);
  }
  else
  {
    if ( !v8 )
    {
      while ( 1 )
        ;
    }
    v9 = _ReadStatusReg(SCTLR_EL1);
    _WriteStatusReg(SCTLR_EL1, v9 & 0xFFFFFFFFFFFFEFFAuLL);
    __isb(0xFu);
    *result = a2;
    __dmb(0xFu);
    __dsb(0xFu);
    __asm { DC              IVAC, X0 }
    __isb(0xFu);
    __asm { TLBI            VMALLE1 }
    __dsb(0xFu);
    __isb(0xFu);
    _WriteStatusReg(SCTLR_EL1, v9 | 0x1005);
    __isb(0xFu);
  }
  _WriteStatusReg(DAIF, StatusReg);
  return result;
}

//----- (00000000000033C4) ----------------------------------------------------
void sub_33C4()
{
  __asm { BR              X2; loc_33F8 }
}
// 5140: using guessed type __int64 qword_5140;

//----- (00000000000034A8) ----------------------------------------------------
__int64 __fastcall sub_34A8(__int64 a1, __int64 a2)
{
  __int64 v4; // x20
  unsigned __int64 v5; // x21
  unsigned __int64 v6; // x22

  v4 = sub_3538();
  v5 = a1 & -v4;
  v6 = a1 + a2;
  while ( v5 < v6 )
  {
    sub_3510();
    v5 += v4;
  }
  sub_3518();
  sub_3520();
  return a1;
}

//----- (0000000000003508) ----------------------------------------------------
void sub_3508()
{
  __asm { DC              IVAC, X0 }
}

//----- (0000000000003510) ----------------------------------------------------
void sub_3510()
{
  __asm { DC              CVAC, X0 }
}

//----- (0000000000003518) ----------------------------------------------------
void sub_3518()
{
  __dsb(0xFu);
}

//----- (0000000000003520) ----------------------------------------------------
void sub_3520()
{
  __isb(0xFu);
}

//----- (0000000000003528) ----------------------------------------------------
__int64 sub_3528()
{
  return 1;
}

//----- (0000000000003530) ----------------------------------------------------
unsigned __int64 sub_3530()
{
  return _ReadStatusReg(CTR_EL0);
}

//----- (0000000000003538) ----------------------------------------------------
__int64 sub_3538()
{
  return (unsigned int)(4 << (((unsigned int)sub_3530() >> 16) & 0xF));
}

//----- (0000000000003558) ----------------------------------------------------
__int64 __fastcall sub_3558(__int64 a1, __int64 a2)
{
  __int64 v2; // x1
  __int64 v3; // x2
  __int64 v4; // x3
  __int64 v5; // x4
  __int64 v6; // x5
  __int64 v7; // x6
  __int64 v8; // x7
  __int64 result; // x0
  __int64 v10; // [xsp+0h] [xbp-10h] BYREF
  __int64 v11; // [xsp+8h] [xbp-8h]

  v11 = qword_5000;
  if ( (*((__int64 (__fastcall **)(__int64, __int64, __int64 *))off_5188 + 8))(a1, a2, &v10) < 0 )
  {
    result = 0;
    v10 = 0;
  }
  else
  {
    result = v10;
  }
  if ( qword_5000 != v11 )
  {
    sub_104C(result, v2, v3, v4, v5, v6, v7, v8, v10);
    return sub_35BC();
  }
  return result;
}
// 35B8: variable 'v2' is possibly undefined
// 35B8: variable 'v3' is possibly undefined
// 35B8: variable 'v4' is possibly undefined
// 35B8: variable 'v5' is possibly undefined
// 35B8: variable 'v6' is possibly undefined
// 35B8: variable 'v7' is possibly undefined
// 35B8: variable 'v8' is possibly undefined
// 35BC: using guessed type __int64 sub_35BC(void);
// 5000: using guessed type __int64 qword_5000;
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (00000000000035BC) ----------------------------------------------------
void __fastcall sub_35BC(__int64 a1, unsigned __int64 a2)
{
  __int64 v3; // x0

  v3 = sub_3558(a1, a2);
  if ( v3 )
    sub_18A8(v3, a2);
}

//----- (00000000000035F0) ----------------------------------------------------
__int64 __fastcall sub_35F0(__int64 a1, unsigned __int64 a2, unsigned __int64 a3, __int64 a4)
{
  __int64 v7; // x0
  __int64 v8; // x20
  unsigned __int64 v9; // x2

  sub_35BC(a1, a3);
  v8 = v7;
  if ( a4 && v7 )
  {
    if ( a2 >= a3 )
      v9 = a3;
    else
      v9 = a2;
    sub_1904(v7, a4, v9);
    sub_3650();
  }
  return v8;
}
// 3614: variable 'v7' is possibly undefined

//----- (0000000000003650) ----------------------------------------------------
void sub_3650()
{
  __int64 v0; // x3
  __int64 v1; // x4
  __int64 v2; // x5
  __int64 v3; // x6
  __int64 v4; // x7
  __int64 v5; // x8
  char vars0; // [xsp+0h] [xbp+0h]

  v5 = (*((__int64 (**)(void))off_5188 + 9))();
  if ( v5 < 0 )
  {
    sub_10AC(0x80000000, "\nASSERT_EFI_ERROR (Status = %r)\n", v5, v0, v1, v2, v3, v4, vars0);
    sub_1440("MemoryAllocationLib.c", 819, "!EFI_ERROR (Status)");
  }
}
// 3688: variable 'v0' is possibly undefined
// 3688: variable 'v1' is possibly undefined
// 3688: variable 'v2' is possibly undefined
// 3688: variable 'v3' is possibly undefined
// 3688: variable 'v4' is possibly undefined
// 3688: variable 'vars0' is possibly undefined
// 5188: using guessed type _UNKNOWN *off_5188;

//----- (00000000000036A8) ----------------------------------------------------
__int64 __fastcall sub_36A8(unsigned __int64 a1, unsigned __int64 a2, __int64 a3)
{
  return sub_35F0(4, a1, a2, a3);
}

//----- (00000000000036C8) ----------------------------------------------------
void __fastcall sub_36C8(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        char a9)
{
  __int64 v9; // x1
  __int64 v10; // x2
  __int64 v11; // x3
  __int64 v12; // x4
  __int64 v13; // x5
  __int64 v14; // x6
  __int64 v15; // x7
  unsigned int v16; // w0
  unsigned __int64 *v17; // x1
  __int64 v18; // x2
  __int64 v19; // x3
  __int64 v20; // x4
  __int64 v21; // x5
  __int64 v22; // x6
  __int64 v23; // x7
  __int64 v24; // [xsp+0h] [xbp-10h] BYREF
  __int64 v25; // [xsp+8h] [xbp-8h]

  v25 = qword_5000;
  sub_3718(0, (unsigned __int64 *)&v24, a3, a4, a5, a6, a7, a8, 0);
  if ( qword_5000 != v25 )
  {
    sub_104C(v24, v9, v10, v11, v12, v13, v14, v15, v24);
    sub_3718(v16, v17, v18, v19, v20, v21, v22, v23, a9);
  }
}
// 3714: variable 'v9' is possibly undefined
// 3714: variable 'v10' is possibly undefined
// 3714: variable 'v11' is possibly undefined
// 3714: variable 'v12' is possibly undefined
// 3714: variable 'v13' is possibly undefined
// 3714: variable 'v14' is possibly undefined
// 3714: variable 'v15' is possibly undefined
// 3715: variable 'v16' is possibly undefined
// 3715: variable 'v17' is possibly undefined
// 3715: variable 'v18' is possibly undefined
// 3715: variable 'v19' is possibly undefined
// 3715: variable 'v20' is possibly undefined
// 3715: variable 'v21' is possibly undefined
// 3715: variable 'v22' is possibly undefined
// 3715: variable 'v23' is possibly undefined
// 5000: using guessed type __int64 qword_5000;

//----- (0000000000003718) ----------------------------------------------------
void __fastcall sub_3718(
        unsigned int a1,
        unsigned __int64 *a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        char a9)
{
  __int64 v11; // x2
  __int64 v12; // x3
  __int64 v13; // x4
  __int64 v14; // x5
  __int64 v15; // x6
  __int64 v16; // x7
  char *v17; // x1
  unsigned __int64 v18; // x0
  char v19; // [xsp+0h] [xbp-10h]

  if ( !sub_3528() )
  {
    sub_10AC(
      0x80000000,
      "Attempt to read ARM Generic Timer registers. But ARM Generic Timer extension is not implemented \n ",
      v11,
      v12,
      v13,
      v14,
      v15,
      v16,
      v19);
    sub_1440("AArch64ArchTimer.c", 94, "0");
    while ( 1 )
      ;
  }
  switch ( a1 )
  {
    case 0u:
      v18 = sub_3814();
      goto LABEL_19;
    case 1u:
      v18 = sub_381C();
      goto LABEL_19;
    case 2u:
      v18 = sub_3824();
      goto LABEL_19;
    case 3u:
      v18 = sub_382C();
      goto LABEL_19;
    case 4u:
      v18 = sub_3834();
      goto LABEL_19;
    case 5u:
      v18 = sub_383C();
      goto LABEL_19;
    case 6u:
      v18 = sub_3844();
      goto LABEL_19;
    case 7u:
      v18 = sub_384C();
      goto LABEL_19;
    case 8u:
      v18 = sub_3854();
      goto LABEL_19;
    case 9u:
      v18 = sub_385C();
      goto LABEL_19;
    case 0xAu:
      v18 = sub_3864();
LABEL_19:
      *a2 = v18;
      return;
    case 0xBu:
    case 0xCu:
    case 0xDu:
    case 0xEu:
      v17 = "The register is related to Hypervisor Mode. Can't perform requested operation\n ";
      goto LABEL_4;
    default:
      v17 = "Unknown ARM Generic Timer register %x. \n ";
      v11 = a1;
LABEL_4:
      sub_10AC(0x80000000, v17, v11, v12, v13, v14, v15, v16, a9);
      return;
  }
}
// 37AC: variable 'v11' is possibly undefined
// 37AC: variable 'v12' is possibly undefined
// 37AC: variable 'v13' is possibly undefined
// 37AC: variable 'v14' is possibly undefined
// 37AC: variable 'v15' is possibly undefined
// 37AC: variable 'v16' is possibly undefined
// 3774: variable 'v19' is possibly undefined

//----- (0000000000003814) ----------------------------------------------------
unsigned __int64 sub_3814()
{
  return _ReadStatusReg(CNTFRQ_EL0);
}

//----- (000000000000381C) ----------------------------------------------------
unsigned __int64 sub_381C()
{
  return _ReadStatusReg(CNTPCT_EL0);
}

//----- (0000000000003824) ----------------------------------------------------
unsigned __int64 sub_3824()
{
  return _ReadStatusReg(CNTKCTL_EL1);
}

//----- (000000000000382C) ----------------------------------------------------
unsigned __int64 sub_382C()
{
  return _ReadStatusReg(CNTP_TVAL_EL0);
}

//----- (0000000000003834) ----------------------------------------------------
unsigned __int64 sub_3834()
{
  return _ReadStatusReg(CNTP_CTL_EL0);
}

//----- (000000000000383C) ----------------------------------------------------
unsigned __int64 sub_383C()
{
  return _ReadStatusReg(CNTV_TVAL_EL0);
}

//----- (0000000000003844) ----------------------------------------------------
unsigned __int64 sub_3844()
{
  return _ReadStatusReg(CNTV_CTL_EL0);
}

//----- (000000000000384C) ----------------------------------------------------
unsigned __int64 sub_384C()
{
  return _ReadStatusReg(CNTVCT_EL0);
}

//----- (0000000000003854) ----------------------------------------------------
unsigned __int64 sub_3854()
{
  return _ReadStatusReg(CNTP_CVAL_EL0);
}

//----- (000000000000385C) ----------------------------------------------------
unsigned __int64 sub_385C()
{
  return _ReadStatusReg(CNTV_CVAL_EL0);
}

//----- (0000000000003864) ----------------------------------------------------
unsigned __int64 sub_3864()
{
  return _ReadStatusReg(CNTVOFF_EL2);
}

// nfuncs=78 queued=74 decompiled=74 lumina nreq=0 worse=0 better=0
// ALL OK, 74 function(s) have been successfully decompiled
